# Generated by Django 3.0.6 on 2020-05-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='作家2')),
            ],
        ),
        migrations.AddField(
            model_name='book2',
            name='authot',
            field=models.ManyToManyField(null=True, to='mystore.Author2'),
        ),
    ]
