# Generated by Django 3.0.6 on 2020-05-28 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0002_auto_20200528_1119'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='myauthor',
        ),
    ]
