# Generated by Django 3.0.6 on 2020-05-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub',
            field=models.CharField(max_length=50, null=True, verbose_name='出版社的名字'),
        ),
    ]
